config/routes.rb
Exercise01::Application.routes.draw do 
  
  scope ":locale", locale: /en|es/ do 
    get "static_pages/home"
    resources :orders
    resources :products        
    resources :users, only: [:new, :create]   
    resources :sessions, only: [:new, :create, :destroy]   
  
    root to: 'static_pages#home'   
  end 
  
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '/', to: 'static_pages#home'
  get '', to: redirect("/")

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <ul class="list-unstyled">
        <li>
          <%= link_to_if(params[:locale] != "en", "[EN]", {locale: :en}) %> |  
          <%= link_to_if(params[:locale] != "es", "[ES]", {locale: :es}) %>
        </li>     
        <li class="pull-right"><%= link_to "<span class='glyphicon glyphicon-share'></span> https://github.com/murtra/shop".html_safe, "https://github.com/murtra/shop"%></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="../" class="navbar-brand">ShopInstant</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">

      <% if current_user %>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to Product.model_name.human(count: 2), products_path %>
        </li>
        <li>
          <%= link_to Order.model_name.human(count: 2), orders_path %>
        </li>
      </ul>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%= link_to "#{t('generic.connected', default: "Connected as")} #{current_user.email}", "/" %>
          </li>
          <li>
            <%= link_to session_path(current_user), :method => :delete do %>
              <i class="glyphicon glyphicon-off"></i> <%= t("generic.close") %>
            <% end %>
          </li>
        <% else%>
          <li><%= link_to t("generic.login"), new_session_path %></li>
          <li><%= link_to t("generic.signup"), new_user_path %></li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopInstant</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= controller.controller_name %>" class="<%= controller.action_name %>">

  <%= render "layouts/header" %>

  <div class="container">
    <div class="page-header" id="banner">
      <div class="row">
        <div class="col-lg-12">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>

    <%= render "layouts/footer" %>

  </div>

</body>
</html>